# Generated by Django 5.0.7 on 2024-09-24 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_message_created_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 20, 28, 21, 882681, tzinfo=datetime.timezone.utc)),
        ),
    ]
