# Generated by Django 5.1.1 on 2025-07-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=15, unique=True, verbose_name='عنوان'),
        ),
    ]
